# Generated by Django 5.2.11 on 2026-06-06 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_fix_learning_user_group_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetype',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null for system types; set to the owning user for custom types.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='resourcetype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', True)), fields=('slug',), name='unique_system_resource_type_slug'),
        ),
        migrations.AddConstraint(
            model_name='resourcetype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', False)), fields=('slug', 'user'), name='unique_user_resource_type_slug'),
        ),
    ]
