# Generated by Django 5.2.11 on 2026-06-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_resource_type_user_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunit',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
