# Generated by Django 5.2.11 on 2026-06-10 21:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_add_completed_at_to_learning_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['user', 'is_archived'], name='lr_user_archived_idx'),
        ),
        migrations.AddIndex(
            model_name='learningunit',
            index=models.Index(fields=['resource', 'status'], name='lu_resource_status_idx'),
        ),
        migrations.AddIndex(
            model_name='learningunit',
            index=models.Index(fields=['resource', 'status', 'updated_at'], name='lu_resource_status_updated_idx'),
        ),
    ]
