# Generated by Django 5.2.11 on 2026-07-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0022_study_session_group_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='status',
            field=models.CharField(choices=[('logged', 'Logged'), ('planned', 'Planned')], default='logged', max_length=10),
        ),
    ]
