# Generated by Django 5.2.11 on 2026-07-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0023_add_study_session_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunit',
            name='reading_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Minutes logged when this chapter was marked complete.', null=True, verbose_name='Reading Time (minutes)'),
        ),
    ]
