# Generated by Django 5.2.11 on 2026-07-08 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0024_learningunit_reading_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_sessions', to='learning.learningunit'),
        ),
    ]
