# Generated by Django 5.2.11 on 2026-07-08 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0025_studysession_unit_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('is_system', models.BooleanField(default=False, help_text='System activities are pre-seeded and shared across all users.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null for system activities; set to the owning user for custom activities.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity',
                'ordering': ['-is_system', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_system', True)), fields=('slug',), name='unique_system_activity_slug'), models.UniqueConstraint(condition=models.Q(('is_system', False)), fields=('slug', 'user'), name='unique_user_activity_slug'), models.CheckConstraint(condition=models.Q(models.Q(('is_system', True), ('user__isnull', True)), models.Q(('is_system', False), ('user__isnull', False)), _connector='OR'), name='activity_system_user_consistent')],
            },
        ),
    ]
