# Generated by Django 5.2.11 on 2026-07-08 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0027_seed_system_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='learning.activity'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='activity_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
