# Generated by Django 5.2.11 on 2026-07-08 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0029_backfill_activity_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysession',
            name='activity_type',
        ),
        migrations.AddField(
            model_name='studysession',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='learning.activity'),
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'logged'), ('unit__isnull', False)), fields=('unit', 'date'), name='ss_unit_date_logged_uniq'),
        ),
    ]
