# Generated by Django 5.2.11 on 2026-07-11 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0030_studysession_finalise_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studysession',
            name='ss_unit_date_logged_uniq',
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'logged'), ('unit__isnull', False)), fields=('unit', 'date', 'activity'), name='ss_unit_date_activity_logged_uniq'),
        ),
    ]
