# Generated by Django 5.2.11 on 2026-08-07 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0031_widen_session_unit_unique_to_include_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('is_system', models.BooleanField(default=False, help_text='System categories are pre-seeded and shared across all users.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null for system categories; set to the owning user for custom categories.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'category',
                'ordering': ['-is_system', 'name'],
            },
        ),
        migrations.AddField(
            model_name='learningresource',
            name='category',
            field=models.ForeignKey(blank=True, help_text="Optional grouping category. Resources with no category are shown under 'Other' on the resources list.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='learning.category'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', True)), fields=('slug',), name='unique_system_category_slug'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', False)), fields=('slug', 'user'), name='unique_user_category_slug'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_system', True), ('user__isnull', True)), models.Q(('is_system', False), ('user__isnull', False)), _connector='OR'), name='category_system_user_consistent'),
        ),
    ]
