# Generated by Django 5.2.11 on 2026-09-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0035_feature_request_group_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyUsageStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("sessions_logged", models.PositiveIntegerField(default=0)),
                ("minutes_logged", models.PositiveIntegerField(default=0)),
                ("active_users", models.PositiveIntegerField(default=0)),
                ("resources_created", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "daily_usage_stat",
                "ordering": ["-date"],
            },
        ),
    ]
