# Generated by Django 5.2.11 on 2026-09-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0036_dailyusagestat"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyusagestat",
            name="active_users_28d",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyusagestat",
            name="active_users_7d",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyusagestat",
            name="total_accounts",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
