# Generated by Django 5.2.11 on 2026-09-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0038_backfill_usage_windows"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRetentionCohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cohort_start", models.DateField(unique=True)),
                ("cohort_size", models.PositiveIntegerField(default=0)),
                ("week_1_retained", models.PositiveIntegerField(blank=True, null=True)),
                ("week_2_retained", models.PositiveIntegerField(blank=True, null=True)),
                ("week_4_retained", models.PositiveIntegerField(blank=True, null=True)),
                ("week_8_retained", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_retention_cohort",
                "ordering": ["-cohort_start"],
            },
        ),
    ]
